name: Auto Merge Dev2 to Main

on:
  push:
    branches:
      - dev2

env:
  MY_REPO: https://SDutta101:${{secrets.GITHUB_TOKEN}}@github.com/SDutta101/jest-test.git
  MY_BRANCH: dev2
  MASTER_REPO: https://github.com/SDutta101/jest-test.git
  MASTER_BRANCH: main

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Branches and Log (Before)
        run: |
          git branch
          git log --oneline --graph -n 5

      - name: Fetch latest changes from origin/main
        run: git fetch origin main

      - name: Fetch latest changes from origin/dev2
        run: git fetch origin dev2

      - name: Verify existence of origin/main
        run: |
          if ! git show-ref --quiet refs/remotes/origin/main; then
            echo "origin/main does not exist."
            exit 1
          fi

      - name: Checkout Main Branch
        run: git checkout -B main origin/main

      - name: Merge dev2 into main
        run: |
          git config user.name "SDutta101"
          git config user.email "saurav11dutta@gmail.com"
          git merge --allow-unrelated-histories origin/dev2 --no-edit

      - name: Handle Merge Conflict
        run: |
          if [ -e "CONFLICT" ]; then
            git checkout --ours .
            git add .
            git commit -m "Automated merge with conflict resolution"
          fi

      - name: Push changes to origin/main
        run: git push --force origin main

      - name: Print Branches and Log (After)
        run: |
          git branch
          git log --oneline --graph -n 5
