name: Auto Merge Dev1 to Main

on:
  push:
    branches:
      - dev1

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Branches and Log (Before)
        run: |
          git branch
          git log --oneline --graph -n 5

      - name: Checkout Main Branch
        run: git checkout main

      - name: Pull changes from origin/main
        run: git pull origin main --no-edit

      - name: Merge dev1 into main
        run: |
          git merge origin/dev1 --no-edit

      - name: Push changes to origin/main
        run: git push --force origin main

      - name: Print Branches and Log (After)
        run: |
          git branch
          git log --oneline --graph -n 5
