name: Auto Merge dev to main

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Branches and Log
        run: |
          git branch
          git log --oneline --graph -n 5

      - name: Check if 'main' branch exists
        run: |
          if ! git show-ref --quiet refs/heads/main; then
            git checkout -b main
            git pull origin main --no-edit
            git push origin main
          fi

      - name: Check if 'dev' branch exists
        run: |
          if ! git show-ref --quiet refs/heads/dev; then
            git checkout -b dev
            git push origin main
          fi

      - name: Merge dev into main
        run: |
          git checkout main
          git pull origin dev --no-edit
          git push origin main
