name: Auto Merge dev to main

on:
  push:
    branches:
      - dev

jobs:
  merge:
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Merge dev into main
        run: |
          git checkout main
          git pull origin dev --no-edit
          git push origin main
