name: Auto Merge dev1 to main

on:
  push:
    branches:
      - dev1

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Branches and Log (Before)
        run: |
          git branch
          git log --oneline --graph -n 5

      - name: Merge dev1 into main
        run: |
          git checkout main
          git pull origin dev1 --no-edit
          git push origin main

      - name: Print Branches and Log (After)
        run: |
          git branch
          git log --oneline --graph -n 5
